INSERT INTO products (id, category, name, dim, notes, price, url, image, blurb, citations, pros, cons, rating, features) VALUES
  ('r1', 'Refrigerator', 'GE 20.8 Cu.Ft. French-Door', '29.75"W x 69.875"H x 36.625"D', 'Ice, no water', 1979, 'https://www.geappliances.com/appliance/GE-ENERGY-STAR-20-8-Cu-Ft-French-Door-Refrigerator-GNE21FYKFS', 'https://cdn11.bigcommerce.com/s-pacto3wrn2/products/273116/images/784403/32ca23b62accb480d40e69ed9e4b58c90edf104d__16707.1756959879.386.513.jpg?c=2', '', '[]', '[]', '[]', 0, '[]'),
  ('r2', 'Refrigerator', 'Blomberg 30" Counter-Depth French Door', '29.75"W x 69.68"H x 27.56"D', 'Ice, no water. Free dishwasher w/ fridge+oven', 2199, 'https://www.klearview.com/products/Blomberg-Appliances/blomb/brfd21622ss.html', 'https://images.webfronts.com/cache/frxlfudpbygc.png?imgeng=/w_300', '', '[]', '[]', '[]', 0, '[]'),
  ('r3', 'Refrigerator', 'Blomberg 30" Panel Ready Bottom Freezer', '29.75"W x 83.5"H x 23.56"D', 'Ice +$250. Free dishwasher w/ fridge+oven', 5999, 'https://www.klearview.com/products/Blomberg-Appliances/blomb/brfb1900fbi.html', 'https://images.webfronts.com/cache/frgdxjfvngnl.jpg?imgeng=/w_300', '', '[]', '[]', '[]', 0, '[]'),
  ('r4', 'Refrigerator', 'GE 21.0 Cu.Ft. Bottom-Freezer', '29.75"W x 69.875"H x 36.625"D', '', 1979, 'https://www.klearview.com/products/GE-Appliances/ge/gde21eykfs.html', 'https://images.webfronts.com/cache/frgeofuyyyib.jpg?imgeng=/w_300', '', '[]', '[]', '[]', 0, '[]'),
  ('d1', 'Dishwasher', 'Bosch 800 Series 24" Fully-Integrated', '23.56"W x 33.875"H x 23.06"D', 'Panel ready. Energy Saver +$150', 1449, 'https://www.klearview.com/products/bosch/shv78dm3n.html', 'https://images.webfronts.com/cache/froibdjmtynb.png?imgeng=/w_300', '', '[]', '[]', '[]', 0, '[]'),
  ('d2', 'Dishwasher', 'GE Profile Panel-Ready Top Control', '23.75"W x 34"H x 24"D', 'Panel ready. Call for price', 0, 'https://www.klearview.com/products/GE-Appliances/ge/pdt715siyii.html', 'https://images.webfronts.com/cache/frhrigwdjgtz.jpg?imgeng=/w_300', '', '[]', '[]', '[]', 0, '[]'),
  ('s1', 'Stove', 'GE 30" Slide-In Gas Double Oven', '30"W x 36.25"H x 29.25"D', 'Electric oven? Rebate available', 2298, 'https://www.klearview.com/products/GE-Appliances/ge/jgss86spss.html', 'https://images.webfronts.com/cache/frdnqqovfmzt.jpg?imgeng=/w_300', '', '[]', '[]', '[]', 0, '[]'),
  ('s2', 'Stove', 'GE Profile 30" Smart Air Fry Convection', '30"W x 36.5"H x 29.5"D', 'Electric oven? Rebate available', 2998, 'https://www.pcrichard.com/ge-profile-30-in-6.7-cu-ft-smart-air-fry-true-european-convection-double-oven-slide-in-gas-range-with-5-sealed-burners-grill-and-griddle-stainless-steel/PGS960YPFS.html', 'https://images.webfronts.com/cache/frhndxbojilv.jpg', '', '[]', '[]', '[]', 0, '[]');
