INSERT OR IGNORE INTO categories (name, sort_order) VALUES
  ('Faucet', 5),
  ('Range Hood', 6),
  ('Washer', 7),
  ('Dryer', 8),
  ('Bathroom Vanity', 9),
  ('Toilet', 10),
  ('Bathroom Faucet', 11),
  ('Shower/Tub', 12),
  ('Bathroom Tile', 13),
  ('Lighting', 14),
  ('Flooring', 15),
  ('Countertops', 16),
  ('Cabinets', 17),
  ('Backsplash', 18),
  ('Cabinet Hardware', 19),
  ('Paint', 20),
  ('Interior Doors', 21),
  ('Window Treatments', 22),
  ('Closet System', 23);
